(function () {
    var levels = [
        {
            "name": "demo level",
            "color": {
                "platform": "#C0C0C0",
            },
            "map": [
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                             oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                                                     ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "   ooooo     1ooooo      ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo                                     ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "ooooooo     X  0     ooooXooo        0   oooooooo        0   oooooooo        0   oooooooo        0   ooo oooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0                                        ",
                "                                                        X                                                                                                                                                                                                                                                                                                                                                                                                                                     ",
                "                                                                                                           o                                                                                                                                                                                                                                                                                                                                                                                  ",
                "                 o   o                         o                                       o               X                                                                                                                                                                                                                                                                                                                                                                                      ",
                "           0                     0                   0                   0              o    0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                                            ",
                "    X                3o            X     3oo                 3 oo                3 o              oo 3                   3                   3                   3                   3                   3                   3                   3                   3                   3                   3                   3                   3                   3                   3                   3                   3                                                     ",
                "         o3o 2       o  XX        2         XXX       2         X         2     o   XX        2      XXXX         2         XX        2                   2                   2                   2                   2                   2                   2                   2                   2                   2                   2                   2                   2                   2                   2                   2                                           ",
                "         XXX                                      X                                                        o                                                                                                                                                                                                                                                                                                                                                                                     ",
                "                                                               o        X            X                                                                                                                                                                                                                                                                                                                                                                                                        ",
                "  oXXX                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ",
                "  X            o                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ",
                " X     X   ooo 0 ooo             ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo                                     "
            ]
        }
    ];

    function getLevelData(i) {
        if (i < levels.length) {
            return levels.slice(0)[i];
        } else {
            throw new Error('There is no data for Level:' + i);
        }
    }

    window.getDataForLevel = getLevelData;
})();