(function () {
    var levels = [
        {
            "name": "demo level",
            "color": {
                "wall": "#70482C",
                "platform": "#C0C0C0",
                "stroke": "#000000"
            },
            "map": [
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                             oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                oooo                                                     ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "   ooooo     1ooooo      ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo    ooooo     1ooooo                                     ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "                        1                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ",
                "                                                                                           1                                      1                                                                                                                                                                                                                                                                                                                                                           ",
                "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
                "ooooooo     X  0     ooooXooo        0   oooooooo        0   oooooooo        0   oooooooo        0   ooo oooo   1    0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0   oooooooo        0                                        ",
                "                                                        X                                                                                                                                                                                                                                                                                                                                                                                                                                     ",
                "                                                                                                           o                                   1                                                                                                                                                                                                                                                                                                                                              ",
                "                 o   o      1                  o                                       o               X                                                                                                                                                                                                                                                                                                                                                                                      ",
                "           0                     0                   0                   0              o    0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                                            ",
                " o3o   X                3o            X     3oo                 3 oo                3 o              oo 3                   3                   3                   3                   3                   3                   3                   3                   3                   3                   3                   3                   3                   3                   3                   3                   3                                                     ",
                " XXX         2       o  XX        2         XXX       2         X         2     o   XX        2      XXXX         2         XX        2         X         2         X         2                   2                   2                   2                   2                   2                   2                   2                   2                   2                   2                   2                   2                   2                                           ",
                "                                               X      X                   X                   X         o                                                                                                                                                                                                                                                                                                                                                                                     ",
                "                                                       1       o        X                                                                                                                                                                                                                                                                                                                                                                                                                    ",
                "  o                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ",
                "              o                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ",
                "          ooo 0 ooo             ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo           ooooooooo                                     "
            ]
        }
    ];

    function getLevelData(i) {
        if (i < levels.length) {
            return levels.slice(0)[i];
        } else {
            throw new Error('There is no data for Level:' + i);
        }
    }

    window.getDataForLevel = getLevelData;
})();